//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _47_Entity_Framework_Data_Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contato
    {
        public int IdContato { get; set; }
        public string Tipo { get; set; }
        public string Contato1 { get; set; }
        public Nullable<int> IdCliente { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
